security:
    # Configuration des hasheurs de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Désactiver la sécurité pour les ressources de développement
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Configuration principale
        main:
            lazy: true
            provider: app_user_provider

            # Formulaire de connexion
            form_login:
                login_path: app_login           # Route vers la page de connexion
                check_path: app_login           # Route pour vérifier les identifiants
                default_target_path: /profile   # Page après connexion
                enable_csrf: true

            # Déconnexion
            logout:
                path: app_logout                # Route pour se déconnecter
                # where to redirect after logout
                # target: app_any_route

    # Contrôle des accès
    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }        # - { path: ^/admin, roles: ROLE_ADMIN }                   # Pages d'administration
        - { path: ^/profile, roles: ROLE_USER }                  # Pages utilisateur
        - { path: ^/banned, roles: ROLE_BANNED }                 # Pages bannies
        - { path: ^/, roles: PUBLIC_ACCESS }                  # Par défaut : accessible uniquement aux utilisateurs connectés
        - { path: ^/logout, roles: ROLE_USER }                  # Par défaut : accessible uniquement aux utilisateurs connectés

when@test:
    security:
        password_hashers:
            # Réduire les coûts pour les tests
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Bcrypt
                time_cost: 3 # Argon
                memory_cost: 10 # Argon
